name: telegram-bot
services:
  - name: bot
    type: web
    build:
      type: docker
    env:
      - name: BOT_TOKEN
        value: "6811502626:AAG9xT3ZQUmg6CrdIPvQ0kCRJ3W5QL-fuZs"
    run:
      command: python3 main.py
